name: Build and Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      # Docker login
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mobile-recharge-app:$IMAGE_TAG .

      # Push image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mobile-recharge-app:$IMAGE_TAG

      # Create deployment package for EB
      - name: Create Dockerrun file
        run: |
          printf '{
            "AWSEBDockerrunVersion": 1,
            "Image": {
              "Name": "%s/mobile-recharge-app:%s",
              "Update": "true"
            },
            "Ports": [
              { "ContainerPort": 8080 }
            ]
          }' "${{ secrets.DOCKER_USERNAME }}" "$IMAGE_TAG" > Dockerrun.aws.json

      # Zip for EB
      - name: Zip bundle
        run: zip deploy.zip Dockerrun.aws.json

      # Deploy to EB
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
